# Site settings
title: JC - Made and Share
email: info@viajc.com
description: A newly started trading company, JC stands for the mission of WE MADE, WE SHARE. A 16-year-old factory and a totally fresh blood of JC team are our asset. We are now largely involved in writing instrument trading, and the position we stand guarantee us to offer a variety of pen styles to suit the needs of all of our customers.
baseurl: ""
url: "http://www.viajc.com"
encoding: utf-8

# Build settings
markdown: kramdown
permalink: none

gems:
  - jekyll-sitemap
