---
products:
    jc-exclusive:
        - file: lumine-jc814
          name: Lumine
          model: JC814
          new: 1
        - file: lumine-jc814sc
          name: Lumine
          model: JC814SC
          new: 1
        - file: erasion-jc807e
          name: Erasion
          model: JC807E
          new: 1
        - file: animal-jc520s
          name: Animal
          model: JC520S
          new: 1
        - file: habilis-stylus-jc417s
          name: Habilis Stylus
          model: JC417S
          new: 1
        - file: linellae-stylus-jc505s
          name: Linellae Stylus
          model: JC505S
          new: 1
        - file: calabash-stylus-jc238s
          name: Calabash Stylus
          model: JC238S
          new: 1
        - file: calabash-jc238
          name: Calabash
          model: JC238
          new: 1
        - file: notes-jc239
          name: Notes
          model: JC239
          new: 1
        - file: big-pen-jc403
          name: Big Pen
          model: JC403
        - file: bunny-jc707
          name: Bunny
          model: JC707
        - file: trangle-jc8012
          name: Trangle
          model: JC8012
        - file: fingers-jc806
          name: Fingers
          model: JC806
        - file: fingers-jc807
          name: Fingers
          model: JC807
        - file: fingers-jc808
          name: Fingers
          model: JC808
        - file: swan-jc702
          name: Swan
          model: JC702
        - file: challenger-jc801
          name: Challenger
          model: JC801
        - file: challenger-jc802
          name: Challenger
          model: JC802
        - file: habilis-jc417
          name: Habilis
          model: JC417
        - file: swan-stylus-jc702s
          name: Swan Stylus
          model: JC702S
        - file: doll-jc573
          name: Doll
          model: JC573
        - file: snowman-jc574
          name: Snowman
          model: JC574
    plastic-ball-pen:
        - file: big-pen-jc403
          name: Big Pen
          model: JC403
        - file: bullet-jc602
          name: Bullet
          model: JC602
        - file: challenger-jc827
          name: Challenger
          model: JC827
        - file: challenger-jc828
          name: Challenger
          model: JC828
        - file: challenger-jc605
          name: Challenger
          model: JC605
        - file: challenger-jc801
          name: Challenger
          model: JC801
        - file: challenger-jc811
          name: Challenger
          model: JC811
        - file: dots-jc812
          name: Dots
          model: JC812
        - file: bunny-jc707
          name: Bunny
          model: JC707
        - file: trangle-jc8012
          name: Trangle
          model: JC8012
        - file: swan-jc702
          name: Swan
          model: JC702
        - file: habilis-jc417
          name: Habilis
          model: JC417
        - file: linellae-jc505
          name: Linellae
          model: JC505
    stylus-pen:
        - file: lumine-jc814sc
          name: Lumine
          model: JC814SC
        - file: animal-jc520s
          name: Animal
          model: JC520
        - file: habilis-stylus-jc417s
          name: Habilis Stylus
          model: JC417S
          new: 1
        - file: linellae-stylus-jc505s
          name: Linellae Stylus
          model: JC505S
          new: 1
        - file: challenger-stylus-jc605s
          name: Challenger Stylus
          model: JC605
        - file: challenger-stylus-jc828s
          name: Challenger Stylus
          model: JC828s
        - file: swan-stylus-jc702s
          name: Swan Stylus
          model: JC 702
    semi-metal-pen:
        - file: silver-touch-jc8011
          name: Silver Touch
          model: JC8011
        - file: silver-touch-jc8013
          name: Silver Touch
          model: JC8013
    cartoon-pen:
        - file: football-jc571s
          name: Football
          model: JC571S
        - file: hook-jc9006
          name: Hook
          model: JC9006
        - file: bunny-jc575
          name: Bunny
          model: JC575
        - file: doll-jc573
          name: Doll
          model: JC573
        - file: football-jc571
          name: Football
          model: JC571
        - file: snowman-jc574
          name: Snowman
          model: JC574
        - file: bear-jc572
          name: Bear
          model: JC572
        - file: chips-jc9027
          name: Chips
          model: JC9027
    novelty-pen:
        - file: fingers-jc806
          name: Fingers
          model: JC806
        - file: fingers-jc807
          name: Fingers
          model: JC807
        - file: fingers-jc808
          name: Fingers
          model: JC808
        - file: qr-pen-jc901
          name: QR pen
          model: JC901
    gel-pen:
        - file: gel-pen-jc334
          name: Gel Pen
          model: JC334
    erasable-pen:
        - file: erasion-jc807e
          name: Erasion
          model: JC807E
          new: 1
    mutifunctional-pen:
        - file: lumine-jc814sc
          name: Lumine
          model: JC814SC
          new: 1
        - file: erasion-jc807e
          name: Erasion
          model: JC807E
          new: 1
