---
products:
    cartoon-pen:
        - bunny-jc575
        - doll-jc573
        - football-jc572
        - snowman-jc574
    plastic-ball-pen:
        - big-pen-jc403
        - bullet-jc602
        - challeneger--jc828
        - challeneger-jc828
        - challeneger-jc605
        - challeneger-jc801
        - challeneger-jc811
        - dots-jc812
        - football-jc571
        - habilis-jc417
        - hawkeye-jc707
        - linellae-jc505
        - trangle-jc8012
        - jcys310
        - jcys321
        - jcys323
    erasable-pen: 
        - erasion-jc807
    gel-pen:
        - jc334
    novelty-pen:
        - fingers-jc806
        - fingers-jc807
    stylus-pen:
        - animal-jc417
        - animal-jc505
        - animal-jc520
        - challeneger-jc605
        - challeneger-jc828
        - challeneger-jc828-m
        - stylus-jc601
        - swan-stylus-jc702
    semi-metal-pen:
        - silver-touch-jc8011
        - silver-touch-jc8013
    eco-pen:
    muti-color-pen:
    jc-exclusive:
        - erasion-jc807
        - animal-jc520
        - animal-jc417
        - animal-jc505
        - bunny-jc575
        - doll-jc573
        - football-jc572
        - snowman-jc574
        - big-pen-jc403
        - bullet-jc602
        - challeneger-jc828-m
        - challeneger-jc828
        - challeneger-jc605
        - challeneger-jc801
        - challeneger-jc811
        - dots-jc812
        - football-jc571
        - hawkeye-jc707
        - trangle-jc8012
        - jc334
        - fingers-jc806
        - fingers-jc807
        - challeneger-jc605
        - challeneger-jc828
        - stylus-jc601
        - habilis-jc417
        - linellae-jc505
        - swan-stylus-jc702
        - silver-touch-jc8011
        - silver-touch-jc8013

