---
products:
    jc-exclusive:
        - file: erasion-jc807
          name: Erasion
          model: JC807
          new: 1
        - file: animal-jc520
          name: Animal
          model: JC520
          new: 1
        - file: habilis-stylus-jc417
          name: Habilis Stylus
          model: JC417
          new: 1
        - file: linellae-stylus-jc505
          name: Linellae Stylus
          model: JC505
          new: 1
        - file: bunny-jc575
          name: Bunny
          model: JC575
        - file: doll-jc573
          name: Doll
          model: JC573
        - file: football-jc571
          name: Football
          model: JC571
        - file: snowman-jc574
          name: Snowman
          model: JC574
        - file: big-pen-jc403
          name: Big Pen
          model: JC403
        - file: bullet-jc602
          name: Bullet
          model: JC602
        - file: challenger-jc827
          name: Challenger
          model: JC827
        - file: challenger-jc828
          name: Challenger
          model: JC828
        - file: challenger-jc605
          name: Challenger
          model: JC605
        - file: challenger-jc801
          name: Challenger
          model: JC801
        - file: challenger-jc811
          name: Challenger
          model: JC811
        - file: dots-jc812
          name: Dots
          model: JC812
        - file: bear-jc572
          name: Bear
          model: JC572
        - file: hawkeye-jc707
          name: Hawkeye
          model: JC707
        - file: trangle-jc8012
          name: Trangle
          model: JC8012
        - file: gel-pen-jc334
          name: Gel pen
          model: JC334
        - file: fingers-jc806
          name: Fingers
          model: JC806
        - file: fingers-jc807
          name: Fingers
          model: JC807
        - file: challenger-stylus-jc605
          name: Challenger Stylus
          model: JC605
        - file: swan-jc702
          name: Swan
          model: JC702
        - file: stylus-jc601
          name: Stylus
          model: JC601
        - file: habilis-jc417
          name: Habilis
          model: JC417
        - file: linellae-jc505
          name: Linellae
          model: JC505
        - file: swan-stylus-jc702
          name: Swan Stylus
          model: JC702
        - file: silver-touch-jc8011
          name: Silver Touch
          model: JC8011
        - file: silver-touch-jc8013
          name: Silver Touch
          model: JC8013
    plastic-ball-pen:
        - file: big-pen-jc403
          name: Big Pen
          model: JC403
        - file: bullet-jc602
          name: Bullet
          model: JC602
        - file: challenger-jc827
          name: Challenger
          model: JC827
        - file: challenger-jc828
          name: Challenger
          model: JC828
        - file: challenger-jc605
          name: Challenger
          model: JC605
        - file: challenger-jc801
          name: Challenger
          model: JC801
        - file: challenger-jc811
          name: Challenger
          model: JC811
        - file: dots-jc812
          name: Dots
          model: JC812
        - file: hawkeye-jc707
          name: Hawkeye
          model: JC707
        - file: trangle-jc8012
          name: Trangle
          model: JC8012
        - file: swan-jc702
          name: Swan
          model: JC702
        - file: habilis-jc417
          name: Habilis
          model: JC417
        - file: linellae-jc505
          name: Linellae
          model: JC505
    stylus-pen:
        - file: animal-jc520
          name: Animal
          model: JC520
        - file: habilis-stylus-jc417
          name: Habilis Stylus
          model: JC417
          new: 1
        - file: linellae-stylus-jc505
          name: Linellae Stylus
          model: JC505
          new: 1
        - file: challenger-stylus-jc605
          name: Challenger Stylus
          model: JC605
        - file: stylus-jc601
          name: Stylus
          model: JC601
        - file: swan-stylus-jc702
          name: Swan Stylus
          model: JC 702
    semi-metal-pen:
        - file: silver-touch-jc8011
          name: Silver Touch
          model: JC8011
        - file: silver-touch-jc8013
          name: Silver Touch
          model: JC8013
    cartoon-pen:
        - file: bunny-jc575
          name: Bunny
          model: JC575
        - file: doll-jc573
          name: Doll
          model: JC573
        - file: football-jc571
          name: Football
          model: JC571
        - file: snowman-jc574
          name: Snowman
        - file: bear-jc572
          name: Bear
          model: JC572
    novelty-pen:
        - file: fingers-jc806
          name: Fingers
          model: JC806
        - file: fingers-jc807
          name: Fingers
          model: JC807
    gel-pen:
        - file: gel-pen-jc334
          name: Gel Pen
          model: JC334
    erasable-pen:
        - file: erasion-jc807
          name: Erasion
          model: JC807
          new: 1
    eco-pen:
    muticolor-pen:
