---
products:
    jc-exclusive:
        - /cartoon/jc-bunny-jc575
        - /cartoon/jc-doll-jc573
        - /cartoon/jc-football-jc572
        - /cartoon/jc-snowman-jc574
    cartoon-pen:
        - bunny-jc575
        - doll-jc573
        - football-jc572
        - snowman-jc574
    plastic-ball-pen:
        - jc-exclusive-challeneger-jc801
        - jcys310
    erasable-pen: 
        - jc-exclusive-erasion-jc807


# jc-exclusive-cartoon, pen-bunny-jc575, jc-exclusive-doll-jc573, jc-exclusive-football-jc572, jc-exclusive-snowman-jc574, jc-exclusive-erasion-jc807, jc-exclusive-jc334, jc-exclusive-big pen-jc403, jc-exclusive-bullet-jc602, jc-exclusive-challeneger-jc828, jc-exclusive-challeneger-jc605, jc-exclusive-challeneger-jc801, jc-exclusive-challeneger-jc811, jc-exclusive-challeneger-jc828, jc-exclusive-dots-812, jc-exclusive-football-jc571, jc-exclusive-habilis-jc417, jc-exclusive-hawkeye-jc707, jc-exclusive-linellae-jc505, jc-exclusive-novelty pen-fingers-jc806, jc-exclusive-novelty pen-fingers-jc807, jc-exclusive-swan stylus-jc702, jc-exclusive-trangle-jc8012, jc-exclusive-semi-metal pen-silver touch-jc8011, jc-exclusive-silver touch-jc8013, jc-exclusive-animal-jc417, jc-exclusive-animal-jc505, jc-exclusive-animal-jc520, jc-exclusive-challeneger-jc605, jc-exclusive-challeneger-jc828, jc-exclusive-stylus-jc601, jc-exclusive-swan stylus-jc702
